# The URL the site will be built for
base_url = "https://adityaaswani.com/"
title = "Aditya Aswani"
description = "Spiritual Friend"
theme = "abridge"

default_language = "en"
compile_sass = true
minify_html = true
build_search_index = false
generate_feeds = true

taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false
smart_punctuation = true

[extra]
# Theme Configuration
title_separator = " | "
title_addition = "Aditya Aswani - Spritual Friend"
email = "hello@adityaaswani.com"
author = "Aditya Aswani"
author_url = "https://adityaaswani.com"

# PWA Configuration
pwa = true
pwa_name = "Aditya Aswani"
pwa_short_name = "Aditya"
pwa_icon_144 = "m144.png"
pwa_icon_192 = "m192.png"
pwa_icon_512 = "m512.png"
pwa_display = "standalone"
pwa_orientation = "portrait"
pwa_scope = "/"
pwa_start_url = "/"

# UI/UX Configuration
theme_switcher = true
back_to_top = true
toc = false
copybtn = true
email_encode = true
hide_page_nextprev_titles = true

# Social Links
social_media_card = true
social = [
    {name = "github", url = "https://github.com/aditya-aswani"},
    {name = "linkedin", url = "https://linkedin.com/in/adityaaswani"},
    {name = "twitter", url = "https://twitter.com/adityaaswani"},
]

# Navigation Menu - now handled by custom template
# menu = []

# SEO and Analytics
keywords = "meditation, mindfulness, software, technology, blog"
meta_keywords = ["meditation", "mindfulness", "software", "technology", "blog"]

# Recent posts configuration
recent = false
recent_items = 5

# Search configuration
search = false
search_library = "elasticlunr"

# Math support
katex = true

# Code highlighting
prism = false

